CREATE TABLE IF NOT EXISTS CASES(
                            `AJBH` VARCHAR(20) NOT NULL COMMENT '案件编号，案件的唯一编号',
                            `AJMC` VARCHAR(20) NOT NULL COMMENT '案件名称',
                            `AJLX` VARCHAR(20) NOT NULL COMMENT '案件类型，[性侵案件，抢劫案件，偷盗案件]',
                            `AJMS` VARCHAR(100) NOT NULL COMMENT '案件描述，对案件现场的描述',
                            `AJDD_S` VARCHAR(100) NOT NULL COMMENT '案件地点-城市，案件发生地点所在的城市，[上海市]',
                            `AJDD_Q` VARCHAR(100) NOT NULL COMMENT '案件地点-区县，案件发生地点所在的区县，[黄浦区，徐汇区，长宁区，静安区，普陀区，虹口区，杨浦区，闵行区，宝山区，嘉定区，浦东新区，金山区，松江区，青浦区，奉贤区，崇明区]',
                            `AJDD` VARCHAR(100) NOT NULL COMMENT '案件地点，案件发生的详细地点',
                            `AJSJ` DATETIME NOT NULL COMMENT '案件时间，案件发生的时间',
                            `XYRXM` VARCHAR(20) NOT NULL COMMENT '嫌疑人姓名',
                            `XYRSFZH` VARCHAR(50) NOT NULL COMMENT '嫌疑人身份证号',
                            `XYRXB` VARCHAR(20) NOT NULL COMMENT '嫌疑人性别，[男，女]',
                            `XYRNL` INT(4) NOT NULL COMMENT '嫌疑人年龄（岁）',
                            `XYRSG` INT(4) NOT NULL COMMENT '嫌疑人身高（cm）',
                            `XYRTZ` INT(4) NOT NULL COMMENT '嫌疑人体重（kg）',
                            `XYRWM` VARCHAR(100) NOT NULL COMMENT '嫌疑人外貌，嫌疑人的外貌描述',
                            `BHRXM` VARCHAR(20) NOT NULL COMMENT '被害人姓名',
                            `BHRSFZH` VARCHAR(50) NOT NULL COMMENT '被害人身份证号',
                            `BHRXB` VARCHAR(20) NOT NULL COMMENT '被害人性别，[男，女]',
                            `BHRNL` INT(4) NOT NULL COMMENT '被害人年龄（岁）',
                            `BHRSG` INT(4) NOT NULL COMMENT '被害人身高（cm）',
                            `BHRTZ` INT(4) NOT NULL COMMENT '被害人体重（kg）',
                            `BHRWM` VARCHAR(100) NOT NULL COMMENT '被害人外貌，被害人的外貌描述',
                            PRIMARY KEY(`AJBH`)
                            )ENGINE=INNODB DEFAULT CHARSET=utf8;